# runtime image including CA certs and tzdata
FROM gcr.io/distroless/static-debian11:latest
# Copy our static executable.
COPY ghouls /go/bin/ghouls
# Expose port for publishing as web service
EXPOSE 8080
# Run the binary.
ENTRYPOINT ["/go/bin/ghouls"]
