---
version: "3"
services:
  ghouls:
    container_name: ghouls
    image: toozej/ghouls:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.ghouls.rule=Host(`ghouls.test`)"
      - "traefik.http.routers.ghouls.middlewares=http-redirect-https@file,headers@file"
      - "traefik.http.routers.ghouls-secure.entrypoints=https"
      - "traefik.http.routers.ghouls-secure.rule=Host(`ghouls.test`)"
      - "traefik.http.routers.ghouls-secure.middlewares=headers@file"
      - "traefik.http.routers.ghouls-secure.tls=true"
    volumes:
      - ghouls:/data
    networks:
      - traefik
